version: '3.5'

services:
  db:
    image: postgres
    restart: always
  web1:
    build: ./bandit
    command: sh /code/run.sh
    volumes:
      - ./bandit:/code
      - /tmp:/tmp

    depends_on:
      - db
  nginx:
      image: nginx:latest
      ports:
        - "8000:8000"
      volumes:
        - /tmp:/tmp
        - ./nginx/:/etc/nginx/conf.d/
      depends_on:
        - web1
